### ISSUE TITLE
Volume is changed on next song

### ISSUE THREAD

**Issue by stucki** [tiliado/nuvola-app-google-play-music#11]
When I started the Google Play Music app, the volume was set to 100%. I've changed the volume down to 50%, and it worked. However, as soon as the next song begins, the volume is back at 100%, and this repeats for every new song.

I'm seeing the volume levels in `pavucontrol`. Changing the volume there works for the current song, but it's changed again for every new song. Inside Nuvola Player, the slider is not changed at all.

Then I noticed that if I change the volume to 0% and hit "reload", then the volume is restored at 0% at every new song from now on. Then I did the same with 6% before hitting reload, and the result was a volume of 39% for every new song. (6 => 39, 8 => 43, 10 => 46). So this is currently the workaround for me, but it seems pretty weird.
##

**Comment by stucki** [comment]
Could it be that something like https://github.com/tiliado/nuvola-app-rdio/pull/3 is needed here?

**Comment by fenryxo** [comment]
Hello @stucki. Thanks for your bug report. I'll probably get around to this issue as a part of the ticket "Check whether a web app volume slider is synchronized with a PulseAudio stream volume" tiliado/nuvolaplayer#139, currently tentatively scheduled for May 2016.

**Comment by fenryxo** [comment]
Hello @stucki, is the issue still reproducible with [Nuvola 4.10.23 and Google Play Music 6.0.5](https://medium.com/nuvola-news/nuvola-4-10-23-325c54a9d494)?

**Comment by fenryxo** [comment]
Closing as expired due to inactivity of the reporter.
