### ISSUE TITLE
Random track skipping

### ISSUE THREAD

**Issue by wedens** [tiliado/nuvola-app-google-play-music#17]
It may stop after some track in playlist with popup`Couldn't play ******. Skipped ahead.` and skip 1 or more tracks.  This problem occurs quite often on multiple computers with arch linux. There is no such problem if I use firefox or chromium to open play music.

`nuvolaplayer3 --debug` output: https://gist.github.com/wedens/7e110c310d4e50b070044661170ce165

Arch Linux x86_64
Nuvola Player R 3.1.0+201607031818.e7c77ba
Revision e7c77ba103b398f1561cf34b6c14b4802cd913d4
WebKitGTK 2.12.3
libsoup 2.54.1
nuvola-app-google-play-music 5.16.r0.g2482276
##

**Comment by fenryxo** [comment]
Hello @wedens. Could you install [GStreamer MP3 plugin](http://tiliado.github.io/nuvolaplayer/documentation/3.0/install-other-linux.html#format-support) and try again?

```
Runner: [WARNING  Nuvola] FormatSupport.vala:108: Your GStreamer installation is missing a plug-in.
gstdecodebin2.c(4565): gst_decode_bin_expose (): /GstPipeline:test-pipeline/GstDecodeBin:decoder:
no suitable plugins found:
Missing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1, layer=(int)3, parsed=(boolean)false)
```

**Comment by wedens** [comment]
same problem :( https://gist.github.com/wedens/44554975dac45ee3f6da7b604092f90d

**Comment by fenryxo** [comment]
Hello. Thanks for the log. Unfortunately, I have no idea what's wrong.

**Comment by fenryxo** [comment]
Does the issue persist with WebKitGTK 2.14?
