### ISSUE TITLE
Application Displays "Loading..."

### ISSUE THREAD

**Issue by coopermor** [tiliado/nuvola-app-google-play-music#19]
After launching Google Play music all that is shown is "Loading..." The console output when opening Nuvola Player 3.0.3 is:

Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Worker: [DEBUG    Nuvola] WebExtension.vala:220: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded about:loading
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.

**Comment by fenryxo** [comment]
Hello @coopermor. Thanks for taking the time to report your issue. I need more information as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)to investigate it further:

* A complete debugging output from a terminal.
* Information about your system.

**Comment by fenryxo** [comment]
Hello @coopermor. I'm closing this issue as I haven't received any response to my request for more information I posted on August 8th, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.
