### ISSUE TITLE
Google Play Music home page is not responding

### ISSUE THREAD

**Issue by pvantonov** [tiliado/nuvola-app-google-play-music#22]
User interface is responding, I can change settings, etc. Only content of web page is frozen.
Nuvola Player 3.0.4
Google Play Music 5.17
[Nuvola console log](https://github.com/tiliado/nuvola-app-google-play-music/files/680811/nuvola.log.txt)
![screenshot from 2017-01-02 20-27-43](https://cloud.githubusercontent.com/assets/12498389/21589983/12b58b78-d12a-11e6-98e5-a897eb924608.png)

**Comment by fenryxo** [comment]
Hello @pvantonov. Thanks for taking the time to report this issue. I'm investigating it at tiliado/nuvolaplayer#279
