### ISSUE TITLE
Can't reach Google Play Reload the page and try again.

### ISSUE THREAD

**Issue by jamiehutber** [tiliado/nuvola-app-google-play-music#23]
I am using Ubuntu 16.04 and the latest version of both nuvola player and this repo.

Suddenly last Friday the Google player stopped working:

![image](https://cloud.githubusercontent.com/assets/1344898/22019050/b240e3ec-dca9-11e6-9ce4-dd8d54b7e090.png)

I am still able to access google music directly in the browser and play music without a problem. However I get the above error.

I am using no special proxy and have never had problems before.

I have re-set the machine, closed and opened Nuvola to try and fix the problem also without any luck.

Can I further debug this for you?

Cheers

**Comment by jamgregory** [comment]
I'm having the same issue - it seems to take Google Play Music a lot longer to load now before the playlist displays, and I'm getting the same 'can't reach Google Play' error :disappointed: 

@fenryxo - are there any logs we can send you to help diagnose what the issue might be?

**Comment by jamiehutber** [comment]
Maybe its a google music "issue" as in, they have blocked third parties, which seems odd to me

**Comment by jamgregory** [comment]
@jamiehutber - hmm, could be. I believe they've implemented such "features" in the past... :disappointed:

**Comment by fenryxo** [comment]
Hello @jamiehutber. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Is the issue reproducible in the [WebKitGTK MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?
* Which [version of Nuvola player](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-nuvola-player-instance) do you use?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* Which version of the Flash plugin do you use? (App Menu → Format support → Web plugins).

**Comment by fenryxo** [comment]
Hello @jamgregory. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Is the issue reproducible in the [WebKitGTK MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?
* Which distribution and version do you use?
* Which [version of Nuvola player](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-nuvola-player-instance) do you use?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* Which version of the Flash plugin do you use? (App Menu → Format support → Web plugins).

**Comment by jamgregory** [comment]
Hey @fenryxo, apologies for the delay. The issue appears to be resolved in Nuvola Player 3.1.1 (I've just updated it now) - hopefully it's fixed for @jamiehutber as well.

**Comment by jamiehutber** [comment]
Thanks for that, I can't find 3.1.1 anywhere :/

**Comment by fenryxo** [comment]
@jamiehutber See [Install Nuvola Player 3.1](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). The recent fixes are going to be backported to the Nuvola 3.0.x series with the 3.0.5 release (tiliado/nuvolaplayer#275) this month.

**Comment by jamiehutber** [comment]
thanks for info @fenryxo but unless you are a developer you cannot do that:
![image](https://cloud.githubusercontent.com/assets/1344898/22784325/8b6b831e-eec7-11e6-86d0-810b14971d55.png)

**Comment by fenryxo** [comment]
Nuvola 3.1 is not only for developers but also for [Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).

**Comment by fenryxo** [comment]
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) git branch. Thanks for making Nuvola Player better by filing bug reports.**

The fix is available in the latest packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html) as well as in the latest [flatpak builds](https://github.com/tiliado/nuvolaplayer/wiki/Flatpaks) of that series. Later, it will be also included in the next bug-fix release of the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html). To get informed when Nuvola Player 3.0.5 Stable Release is released, follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer), [Google+](https://plus.google.com/110794636546911932554) or [Twitter](https://twitter.com/NuvolaPlayer); or subscribe to the [Nuvola Player Newsletter](http://eepurl.com/bLbtM1).

**Comment by fenryxo** [comment]
[Nuvola Player 3.0.5 and Diorite 0.2.2 has been released.](https://medium.com/nuvola-news/nuvola-player-3-0-5-and-diorite-0-2-2-released-c170dfb53130)
